name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn init -y
          yarn add --dev prettier prettylint
          yarn prettylint .
