name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  enforce-versioing:
  runs-on: ubuntu-latest
  steps:
    - name: Enforce PR title format and extract bump type
      uses: ./.github/actions/get_sematic_versioning
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn init -y
          yarn add --dev prettier prettylint
          yarn prettylint .
