name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn init -y
          yarn add --dev prettier prettylint
          yarn prettylint .

  release:
    runs-on: ubuntu-latest
    needs:
      - prettier
    steps:
      - uses: actions/checkout@v4
      - name: Upload new mod version
        uses: ./.github/actions/steam_workshop_upload
        with:
          steam_username: ${{ secrets.STEAM_USERNAME }}
          steam_password: ${{ secrets.STEAM_PASSWORD }}
          game_id: '1158310'
          mod_id: '3479625504'
          workshop_visibility: '2' # private
          workshop_title: 'Custom Labs'
          workshop_description: 'A simple mod satisfying my need to min-max cultures, religions and other stuff in CK3.'
