name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: Get bump type from PR title
        uses: ./.github/actions/get_sematic_versioning
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.bump_type }}
          tag_prefix: v

      - name: Update version in descriptor.mod
        run: |
          VERSION=${{ steps.tag.outputs.new_version }}

          echo "🔧 Updating descriptor.mod to version $VERSION"

          sed -i -E 's/^version="[^"]+"/version="'"$VERSION"'"/' mod/descriptor.mod

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mod/descriptor.mod
          git commit -m "Update release version to $VERSION"
          git push origin HEAD

      - name: Add tag to last commit
        run: |
          git tag -f ${{ steps.tag.outputs.new_tag }}
          git push origin ${{ steps.tag.outputs.new_tag }} --force
