name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: |
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.bump_type }} # Use the bump type detected from PR title
          tag_prefix: v

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: Release ${{ steps.tag.outputs.new_tag }}
          body: |
            Release created from PR: ${{ github.event.pull_request.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update "latest" tag to this release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f latest ${{ steps.tag.outputs.new_tag }}  # Point "latest" to new release tag
          git push origin latest --force

      - name: Upload new mod version
        uses: ./.github/actions/steam_workshop_upload
        with:
          steam_username: ${{ secrets.STEAM_USERNAME }}
          steam_password: ${{ secrets.STEAM_PASSWORD }}
          game_id: '1158310'
          mod_id: '3479625504'
          workshop_visibility: '2' # private
          workshop_title: 'Custom Labs'
          workshop_description: 'A simple mod satisfying my need to min-max cultures, religions, and other stuff in CK3.'
